"""Generate docs/PROMPTS.md: the composed system prompt of every agent.

    python examples/dump_prompts.py [DIRETÓRIO] [-o SAÍDA]

A prompt in OAF is not a file — it is composed. The Markdown body of AGENTS.md
is what the author wrote; everything after it is generated by the harness from
the manifest's composition blocks. This script writes both, marking the seam, so
what an agent actually receives can be read without running one.

Because the output is generated, it can drift from the agents it describes.
`tests/test_prompts.py` regenerates it and fails if the committed file differs.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from oaf.resolve import ResolvedAgent, Workspace, resolve_agent
from oaf.runtime import build_system_prompt, resolve_model
from oaf.runtime.prompt import skill_mode_for

RAIZ = Path(__file__).resolve().parent.parent
PADRAO_ENTRADA = RAIZ / "tribe"
PADRAO_SAIDA = RAIZ / "docs" / "PROMPTS.md"

#: Sections build_system_prompt appends after the authored body.
GERADAS = (
    "## Available Skills",
    "## Connected MCP Servers",
    "## Delegation",
    "## Tool Restrictions",
)

CABECALHO = """# Prompts compostos

O prompt de um agente OAF **não é um arquivo** — ele é composto. O corpo Markdown
do `AGENTS.md` é o que o autor escreveu; tudo depois dele o harness gera a partir
dos blocos de composição do manifesto.

```
corpo do AGENTS.md          ← autorado
## Available Skills         ← gerado de skills:
## Connected MCP Servers    ← gerado de mcpServers: + ActiveMCP.json
## Delegation               ← gerado de agents:
## Tool Restrictions        ← gerado de config.tools.denied
```

Este arquivo é **gerado**. Para regerá-lo:

```bash
python examples/dump_prompts.py
```

Para ver um agente só, sem gerar nada:

```bash
oaf inspect tribe/manager --prompt
```

> **O que não está aqui.** Sob *progressive disclosure*, o corpo de uma skill
> **não** entra no prompt inicial — só o nome, a descrição e a lista de arquivos.
> O corpo chega quando o agente chama `load_skill(nome)`. É por isso que um
> agente com uma skill de 4 KB tem um prompt de 1,5 KB.
"""


def _dividir(resolvido: ResolvedAgent, prompt: str) -> tuple[str, str]:
    """Split a composed prompt into its authored and generated halves."""
    autorado = resolvido.document.system_prompt.strip()
    if prompt.startswith(autorado):
        return autorado, prompt[len(autorado):].strip()
    # Should not happen, but a wrong split must not be silent.
    return prompt, ""


def _ancora(heading: str) -> str:
    """GitHub's anchor rule: lowercase, punctuation dropped, spaces to hyphens.

    Hyphens survive — only the slash is punctuation here, so `tribe/dados-planner`
    becomes `tribedados-planner`, not `tribedadosplanner`.
    """
    texto = re.sub(r"[^\w\s-]", "", heading.strip().lower(), flags=re.UNICODE)
    return texto.replace(" ", "-")


def _secoes_geradas(gerado: str) -> list[str]:
    return [s for s in GERADAS if s in gerado]


def gerar(raiz: Path) -> str:
    workspace = Workspace.from_path(raiz)
    agentes = sorted(workspace.agents, key=lambda a: a.canonical_slug)
    if not agentes:
        raise SystemExit(f"nenhum agente encontrado em {raiz}")

    partes = [CABECALHO, "\n## Índice\n", "| Agente | Papel | Modelo | Tamanho | Seções geradas |",
              "|---|---|---|---|---|"]

    corpos = []
    for agente in agentes:
        resolvido = resolve_agent(agente, workspace=workspace)
        prompt = build_system_prompt(resolvido)
        autorado, gerado = _dividir(resolvido, prompt)
        modelo = resolve_model(agente.manifest, environ={})
        secoes = _secoes_geradas(gerado)
        slug = agente.canonical_slug
        ancora = _ancora(slug)

        partes.append(
            f"| [`{slug}`](#{ancora}) | {agente.manifest.tags[0] if agente.manifest.tags else '—'} "
            f"| `{modelo.name}` | {len(prompt)} chars "
            f"| {', '.join(s.removeprefix('## ') for s in secoes) or '—'} |"
        )

        # Blank lines between blocks, or the blockquote becomes a lazy
        # continuation of the line above it and the metadata renders as prose.
        cabeca = [
            f"## {slug}",
            f"**{agente.manifest.name}** · v{agente.manifest.version} · "
            f"`{modelo}` · formato `{resolvido.document.instruction_format}` · "
            f"skills `{skill_mode_for(resolvido)}`",
            f"> {agente.manifest.description}",
        ]
        if agente.manifest.skills:
            nomes = ", ".join(f"`{s.name}`" for s in agente.manifest.skills)
            cabeca.append(f"**Skills:** {nomes}")
        if agente.manifest.agents:
            nomes = ", ".join(f"`{s.slug}` ({s.role})" for s in agente.manifest.agents)
            cabeca.append(f"**Delega a:** {nomes}")

        cabeca.append(f"### Corpo autorado — `{agente.root.name}/AGENTS.md`")
        cabeca.append(f"````markdown\n{autorado}\n````")
        cabeca.append("### Composto pelo harness")
        cabeca.append(
            f"````markdown\n{gerado}\n````" if gerado
            else "*Nada — este agente não declara skills, MCP, sub-agentes nem tools negadas.*"
        )
        corpos.append("---\n\n" + "\n\n".join(cabeca) + "\n")

    partes.append("")
    partes.extend(corpos)
    return "\n".join(partes).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("raiz", type=Path, nargs="?", default=PADRAO_ENTRADA,
                        metavar="DIRETÓRIO", help="onde procurar agentes")
    parser.add_argument("-o", "--output", type=Path, default=PADRAO_SAIDA,
                        metavar="ARQUIVO", help="onde escrever")
    parser.add_argument("--stdout", action="store_true",
                        help="imprime em vez de escrever no arquivo")
    args = parser.parse_args(argv)

    conteudo = gerar(args.raiz)
    if args.stdout:
        print(conteudo, end="")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(conteudo, encoding="utf-8")
    print(f"{len(conteudo)} chars -> {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
